name: Push Docker Image

on:
  push:
    branches: main
    paths:
      - .github/workflows/build.yml
      - .github/workflows/deploy.yml
      - .dockerignore
      - Dockerfile.build
      - poetry.lock
      - pyproject.toml
      - '**.py'
      - '**.html'
    workflow_dispatch:

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          show-progress: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest



  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          show-progress: false

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile.build
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  restart:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Factory restart API
        run: |
          curl -X POST https://huggingface.co/api/spaces/$GITHUB_REPOSITORY/restart?factory=true \
               -H "Authorization: Bearer $HF_TOKEN"
